version: "3.9"

services:
  api:
    build: .
    command: python -m app.main
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  bot:
    build: .
    command: python -m bot.main
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
