version: "3.9"

services:
  api:
    build: .
    command: python -m app.main
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  bot:
    build: .
    command: python -m bot.main
    env_file:
      - .env
    restart: unless-stopped
