name: Quality & CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev-requirements.txt

      - name: Create .env from secrets
        run: |
          echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Run ruff
        run: |
          ruff check .

      - name: Check formatting (black)
        run: |
          black --check .

      - name: Check import order (isort)
        run: |
          isort --check-only .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev-requirements.txt

      - name: Create .env from secrets
        run: |
          echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Run tests
        run: |
          pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from secrets
        run: |
          echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Copy project to server
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.API_HOST }}:~/autoresolver/

      - name: Deploy via docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/autoresolver
            docker compose down || true
            docker compose build
            docker compose up -d
